// ============================================================
// SynaptiVerse - Neo4j Knowledge Graph Seed
// 202 Conditions | 120 canonical symptom nodes | Nigeria-focused aliases
// Safe to re-run with cypher-shell or APOC because all data writes use MERGE.
// ============================================================

CREATE CONSTRAINT symptom_id IF NOT EXISTS FOR (s:Symptom) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT condition_id IF NOT EXISTS FOR (c:Condition) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT specialty_id IF NOT EXISTS FOR (sp:Specialty) REQUIRE sp.id IS UNIQUE;
CREATE CONSTRAINT urgency_level IF NOT EXISTS FOR (u:Urgency) REQUIRE u.level IS UNIQUE;

MATCH (n) DETACH DELETE n;

UNWIND ['CRITICAL', 'URGENT', 'ROUTINE'] AS level
MERGE (:Urgency {level: level});

UNWIND [
  {id: 'SP001', name: 'Cardiologist'},
  {id: 'SP002', name: 'General Practitioner'},
  {id: 'SP003', name: 'Neurologist'},
  {id: 'SP004', name: 'Pulmonologist'},
  {id: 'SP005', name: 'Gastroenterologist'},
  {id: 'SP006', name: 'Infectious Disease Specialist'},
  {id: 'SP007', name: 'Nephrologist'},
  {id: 'SP008', name: 'Endocrinologist'},
  {id: 'SP009', name: 'Orthopedic Surgeon'},
  {id: 'SP010', name: 'Dermatologist'},
  {id: 'SP011', name: 'Ophthalmologist'},
  {id: 'SP012', name: 'ENT Specialist'},
  {id: 'SP013', name: 'Obstetrician/Gynecologist'},
  {id: 'SP014', name: 'Pediatrician'},
  {id: 'SP015', name: 'Psychiatrist'},
  {id: 'SP016', name: 'Urologist'},
  {id: 'SP017', name: 'Hematologist'},
  {id: 'SP018', name: 'Oncologist'},
  {id: 'SP019', name: 'Rheumatologist'},
  {id: 'SP020', name: 'Emergency Medicine'},
  {id: 'SP021', name: 'Surgeon'},
  {id: 'SP022', name: 'Dentist'}
] AS row
MERGE (sp:Specialty {id: row.id})
SET sp.name = row.name;

UNWIND [
  {id: 'S001', name: 'chest pain', aliases: ['my chest dey pain me', 'chest dey tight', 'pain for chest']},
  {id: 'S002', name: 'shortness of breath', aliases: ['I no fit breathe well', 'breath don short', 'I dey struggle breathe']},
  {id: 'S003', name: 'palpitations', aliases: ['my heart dey beat fast', 'heart dey jump', 'heart racing']},
  {id: 'S004', name: 'leg swelling', aliases: ['my leg don swell', 'leg big', 'water for leg']},
  {id: 'S005', name: 'dizziness', aliases: ['my head dey turn', 'I dey feel dizzy', 'everything dey spin']},
  {id: 'S006', name: 'fainting', aliases: ['I fall down', 'I black out', 'I no dey remember wetin happen']},
  {id: 'S007', name: 'jaw pain', aliases: ['my jaw dey pain', 'pain for jaw']},
  {id: 'S008', name: 'left arm pain', aliases: ['my left hand dey pain', 'left arm dey pain me']},
  {id: 'S009', name: 'severe headache', aliases: ['head dey pain me well well', 'serious headache', 'my head go burst']},
  {id: 'S010', name: 'sudden confusion', aliases: ['I dey confuse', 'I no know wetin happen', 'person don dey talk anyhow']},
  {id: 'S011', name: 'facial drooping', aliases: ['face don bend', 'one side of face fall down']},
  {id: 'S012', name: 'arm weakness', aliases: ['my hand weak', 'I no fit raise my hand', 'hand no dey work']},
  {id: 'S013', name: 'slurred speech', aliases: ['I no fit talk well', 'tongue heavy', 'speech don change']},
  {id: 'S014', name: 'seizure', aliases: ['I dey shake', 'body dey shake', 'convulsion', 'I don fall and shake']},
  {id: 'S015', name: 'memory loss', aliases: ['I dey forget things', 'memory don go', 'I no fit remember']},
  {id: 'S016', name: 'numbness in limbs', aliases: ['my hand or leg dey numb', 'I no feel my leg', 'pins and needles']},
  {id: 'S017', name: 'blurred vision', aliases: ['I no fit see well', 'my eye don blur', 'everything foggy']},
  {id: 'S018', name: 'loss of consciousness', aliases: ['person don faint', 'dem no dey respond', 'person don lose sense']},
  {id: 'S019', name: 'high fever', aliases: ['body hot well well', 'temperature high', 'I get serious fever', 'body on fire']},
  {id: 'S020', name: 'chills', aliases: ['I dey shiver', 'cold dey catch me', 'I dey shake with cold']},
  {id: 'S021', name: 'sweating', aliases: ['I dey sweat plenty', 'sweat plenty for body', 'night sweat']},
  {id: 'S022', name: 'body aches', aliases: ['my whole body dey pain', 'body pain everywhere', 'bone dey pain me']},
  {id: 'S023', name: 'fatigue', aliases: ['I dey weak', 'I tire well well', 'no energy', 'I dey feel anyhow']},
  {id: 'S024', name: 'loss of appetite', aliases: ['I no want chop', 'food no sweet again', 'I no hungry']},
  {id: 'S025', name: 'nausea', aliases: ['I dey feel like vomit', 'stomach dey turn', 'I wan puke']},
  {id: 'S026', name: 'vomiting', aliases: ['I don vomit', 'I don purge from mouth', 'I throw up']},
  {id: 'S027', name: 'joint pain', aliases: ['my joint dey pain', 'waist and joint dey pain', 'joint stiff']},
  {id: 'S028', name: 'diarrhea', aliases: ['I dey run stomach', 'I dey go toilet plenty', 'loose stool', 'my yansh dey run']},
  {id: 'S029', name: 'bloody diarrhea', aliases: ['blood dey my stool', 'I see blood when I go toilet', 'stool with blood']},
  {id: 'S030', name: 'abdominal pain', aliases: ['my stomach dey pain', 'belle dey pain me', 'tummy pain']},
  {id: 'S031', name: 'right lower abdominal pain', aliases: ['pain for right side of my belly', 'right belly pain sharp']},
  {id: 'S032', name: 'bloating', aliases: ['my belle don blow up', 'stomach dey full up', 'gas for stomach']},
  {id: 'S033', name: 'constipation', aliases: ['I no fit shit', 'stool hard', 'I no dey go toilet']},
  {id: 'S034', name: 'heartburn', aliases: ['chest dey burn', 'acid dey rise', 'food dey come back up']},
  {id: 'S035', name: 'black tarry stool', aliases: ['black stool', 'my shit don change color', 'dark stool']},
  {id: 'S036', name: 'jaundice', aliases: ['my eye don turn yellow', 'skin dey yellow', 'yellow eyes']},
  {id: 'S037', name: 'pale stool', aliases: ['stool don turn white', 'stool color change']},
  {id: 'S038', name: 'cough', aliases: ['I dey cough', 'cough dey disturb me', 'I get cough']},
  {id: 'S039', name: 'productive cough', aliases: ['I dey cough out something', 'I cough sputum', 'I cough mucus']},
  {id: 'S040', name: 'blood in cough', aliases: ['blood dey my cough', 'I cough out blood', 'red thing dey when I cough']},
  {id: 'S041', name: 'wheezing', aliases: ['my chest dey make noise', 'I dey wheeze', 'whistling sound when I breathe']},
  {id: 'S042', name: 'night sweats', aliases: ['I dey sweat for night', 'I wake up wet']},
  {id: 'S043', name: 'weight loss', aliases: ['I don lose weight', 'I don slim', 'my body don go down']},
  {id: 'S044', name: 'painful urination', aliases: ['urine dey pain me', 'it pain when I piss', 'burning when I pee']},
  {id: 'S045', name: 'frequent urination', aliases: ['I dey piss too much', 'I dey urinate plenty', 'toilet too frequent']},
  {id: 'S046', name: 'blood in urine', aliases: ['I see blood for my urine', 'my piss red', 'blood for wee wee']},
  {id: 'S047', name: 'lower back pain', aliases: ['my back dey pain', 'waist dey pain me', 'back pain']},
  {id: 'S048', name: 'inability to urinate', aliases: ['I no fit piss', 'urine no dey come out', 'I dey struggle to pee']},
  {id: 'S049', name: 'flank pain', aliases: ['side pain', 'pain for side of my back', 'kidney area pain']},
  {id: 'S050', name: 'foamy urine', aliases: ['urine dey foam', 'my piss look like soap water']},
  {id: 'S051', name: 'skin rash', aliases: ['rash dey my body', 'I get rash', 'pimple-like thing for skin']},
  {id: 'S052', name: 'itching', aliases: ['my body dey itch', 'scratch scratch', 'I dey scratch everywhere']},
  {id: 'S053', name: 'skin peeling', aliases: ['my skin dey peel', 'skin don start remove']},
  {id: 'S054', name: 'wound not healing', aliases: ['my wound no dey heal', 'cut no dey close', 'sore dey remain']},
  {id: 'S055', name: 'boil or abscess', aliases: ['boil dey my body', 'I get boil', 'painful lump for skin']},
  {id: 'S056', name: 'skin darkening', aliases: ['my skin dey change', 'skin don turn darker']},
  {id: 'S057', name: 'eye redness', aliases: ['my eye red', 'eye don turn red', 'red eye']},
  {id: 'S058', name: 'eye discharge', aliases: ['something dey come out my eye', 'eye dey produce', 'pus from eye']},
  {id: 'S059', name: 'eye pain', aliases: ['my eye dey pain', 'eye pain me']},
  {id: 'S060', name: 'sudden vision loss', aliases: ['I don blind suddenly', 'my eye don go', 'I no fit see suddenly']},
  {id: 'S061', name: 'seeing floaters', aliases: ['I dey see things wey dey float', 'spots for my eye']},
  {id: 'S062', name: 'sore throat', aliases: ['throat dey pain me', 'I get sore throat', 'swallow pain me']},
  {id: 'S063', name: 'ear pain', aliases: ['my ear dey pain', 'ear pain me', 'pain inside ear']},
  {id: 'S064', name: 'ear discharge', aliases: ['something dey come out my ear', 'ear dey leak', 'pus from ear']},
  {id: 'S065', name: 'hearing loss', aliases: ['I no fit hear', 'my ear don block', 'sound no dey clear']},
  {id: 'S066', name: 'runny nose', aliases: ['my nose dey run', 'mucus dey come from nose', 'catarrh']},
  {id: 'S067', name: 'nasal congestion', aliases: ['my nose don block', 'I no fit breathe from nose', 'blocked nose']},
  {id: 'S068', name: 'sneezing', aliases: ['I dey sneeze plenty', 'sneeze no stop']},
  {id: 'S069', name: 'hoarse voice', aliases: ['my voice don change', 'voice hoarse', 'I no fit talk loud']},
  {id: 'S070', name: 'difficulty swallowing', aliases: ['swallow hard', 'food no dey go down well', 'I dey struggle swallow']},
  {id: 'S071', name: 'swollen joint', aliases: ['joint don swell', 'my knee don swell', 'swelling for joint']},
  {id: 'S072', name: 'bone pain', aliases: ['my bone dey pain', 'deep pain inside leg', 'pain wey reach bone']},
  {id: 'S073', name: 'back stiffness', aliases: ['my back stiff', 'I no fit bend', 'morning stiffness']},
  {id: 'S074', name: 'muscle cramps', aliases: ['my muscle dey cramp', 'leg cramp', 'muscle pull']},
  {id: 'S075', name: 'difficulty walking', aliases: ['I no fit walk well', 'walking pain me', 'I dey limp']},
  {id: 'S076', name: 'heavy menstrual bleeding', aliases: ['period too much', 'I dey lose too much blood', 'period no dey stop']},
  {id: 'S077', name: 'missed period', aliases: ['period no come', 'my period don miss', 'I no see period']},
  {id: 'S078', name: 'vaginal discharge', aliases: ['something dey come from down there', 'discharge dey my vagina', 'I see discharge']},
  {id: 'S079', name: 'pelvic pain', aliases: ['pain for my private area', 'down belly pain', 'waist and private pain']},
  {id: 'S080', name: 'pregnancy with high blood pressure', aliases: ['I dey pregnant and BP high', 'blood pressure high during pregnancy']},
  {id: 'S081', name: 'pregnancy with swollen face and hands', aliases: ['face and hand swell during pregnancy', 'I dey pregnant my face swell']},
  {id: 'S082', name: 'painful periods', aliases: ['period pain too much', 'cramp dey during period', 'dysmenorrhea']},
  {id: 'S083', name: 'child with high fever', aliases: ['pikin body hot', 'my pikin get fever', 'baby temperature high']},
  {id: 'S084', name: 'child not eating', aliases: ['pikin no want chop', 'my pikin refuse food', 'baby no dey eat']},
  {id: 'S085', name: 'child with rash', aliases: ['pikin get rash', 'rash dey pikin body', 'my baby skin dey peel']},
  {id: 'S086', name: 'child with diarrhea', aliases: ['pikin dey purge', 'baby stool too watery', 'pikin dey go toilet plenty']},
  {id: 'S087', name: 'child crying excessively', aliases: ['pikin no stop cry', 'baby dey cry too much', 'my pikin dey wail']},
  {id: 'S088', name: 'child with convulsion', aliases: ['pikin dey shake', 'baby get convulsion', 'pikin body dey twitch']},
  {id: 'S089', name: 'persistent sadness', aliases: ['I dey sad always', 'no happiness', 'I dey feel down every day']},
  {id: 'S090', name: 'anxiety', aliases: ['I dey worry too much', 'fear dey catch me', 'I dey anxious']},
  {id: 'S091', name: 'hearing voices', aliases: ['I dey hear voice nobody dey', 'voice dey talk to me', 'I dey hear things']},
  {id: 'S092', name: 'sleep disturbance', aliases: ['I no fit sleep', 'sleep no dey come', 'I dey wake up at night']},
  {id: 'S093', name: 'suicidal thoughts', aliases: ['I wan die', 'I dey think about ending my life', 'I no want live again']},
  {id: 'S094', name: 'excessive thirst', aliases: ['I dey drink water too much', 'thirst no dey stop', 'I always dey thirsty']},
  {id: 'S095', name: 'excessive hunger', aliases: ['I always hungry', 'I just chop and I hungry again', 'hunger no dey stop']},
  {id: 'S096', name: 'trembling', aliases: ['my hand dey shake', 'I dey tremble', 'body dey vibrate']},
  {id: 'S097', name: 'heat intolerance', aliases: ['heat dey disturb me too much', 'I dey sweat for small heat']},
  {id: 'S098', name: 'cold intolerance', aliases: ['small cold dey disturb me', 'I dey feel cold always']},
  {id: 'S099', name: 'goiter', aliases: ['swelling for neck', 'lump for throat area', 'my neck don swell']},
  {id: 'S100', name: 'low blood sugar symptoms', aliases: ['I dey shake and sweat', 'sugar don drop', 'I dey weak and confused']},
  {id: 'S101', name: 'pallor', aliases: ['my body wan turn white', 'I look pale', 'my lip don pale']},
  {id: 'S102', name: 'easy bruising', aliases: ['I dey bruise easy', 'my skin dey bruise for nothing', 'bruise appear without injury']},
  {id: 'S103', name: 'prolonged bleeding', aliases: ['cut dey bleed long time', 'wound no dey stop bleed', 'blood no wan stop']},
  {id: 'S104', name: 'bone pain in legs', aliases: ['my leg bone dey pain bad', 'deep pain for leg and back']},
  {id: 'S105', name: 'yellowing of eyes', aliases: ['my eye don turn yellow', 'yellow eye', 'jaundice eye']},
  {id: 'S106', name: 'swollen lymph nodes', aliases: ['lump for neck', 'swelling under armpit', 'lump for groin area']},
  {id: 'S107', name: 'snake bite', aliases: ['snake bite me', 'I don get snake bite', 'fang mark for my body']},
  {id: 'S108', name: 'severe burn', aliases: ['fire burn me', 'I don burn myself', 'hot water pour my body']},
  {id: 'S109', name: 'fracture', aliases: ['bone don break', 'I think my bone break', 'my hand/leg don break']},
  {id: 'S110', name: 'head injury', aliases: ['I fall and my head hit', 'accident and head knock', 'head wound']},
  {id: 'S111', name: 'neck stiffness', aliases: ['my neck stiff', 'I no fit bend my neck', 'neck dey pain and stiff']},
  {id: 'S112', name: 'light sensitivity', aliases: ['light dey disturb my eye', 'I no fit look light', 'light dey pain my eye']},
  {id: 'S113', name: 'rash with fever', aliases: ['fever and rash together', 'I get rash and body hot']},
  {id: 'S114', name: 'genital sore', aliases: ['sore for my private', 'wound for down there', 'painful sore for genital']},
  {id: 'S115', name: 'penile discharge', aliases: ['something dey come from my joystick', 'discharge from private', 'pus from penis']},
  {id: 'S116', name: 'tooth pain', aliases: ['my tooth dey pain', 'toothache', 'pain for my mouth']},
  {id: 'S117', name: 'gum swelling', aliases: ['my gum swell', 'gum dey pain and swell']},
  {id: 'S118', name: 'frequent urination at night', aliases: ['I dey wake up plenty times to piss for night', 'nocturia']},
  {id: 'S119', name: 'dark urine', aliases: ['my urine don turn dark', 'piss dey brown or orange', 'urine color change']},
  {id: 'S120', name: 'sudden weight gain', aliases: ['I don gain weight fast', 'body don swell up quick']}
] AS row
MERGE (s:Symptom {id: row.id})
SET s.name = row.name,
    s.pidgin_aliases = row.aliases;

UNWIND [
  {id: 'C001', name: 'Acute Myocardial Infarction (Heart Attack)', specialty: 'SP001', urgency: 'CRITICAL'},
  {id: 'C002', name: 'Hypertensive Crisis', specialty: 'SP001', urgency: 'CRITICAL'},
  {id: 'C003', name: 'Heart Failure', specialty: 'SP001', urgency: 'URGENT'},
  {id: 'C004', name: 'Arrhythmia', specialty: 'SP001', urgency: 'URGENT'},
  {id: 'C005', name: 'Angina Pectoris', specialty: 'SP001', urgency: 'URGENT'},
  {id: 'C006', name: 'Pericarditis', specialty: 'SP001', urgency: 'URGENT'},
  {id: 'C007', name: 'Infective Endocarditis', specialty: 'SP001', urgency: 'URGENT'},
  {id: 'C008', name: 'Aortic Dissection', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C009', name: 'Deep Vein Thrombosis', specialty: 'SP001', urgency: 'URGENT'},
  {id: 'C010', name: 'Pulmonary Embolism', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C011', name: 'Ischemic Stroke', specialty: 'SP003', urgency: 'CRITICAL'},
  {id: 'C012', name: 'Hemorrhagic Stroke', specialty: 'SP003', urgency: 'CRITICAL'},
  {id: 'C013', name: 'Transient Ischemic Attack (TIA)', specialty: 'SP003', urgency: 'URGENT'},
  {id: 'C014', name: 'Bacterial Meningitis', specialty: 'SP003', urgency: 'CRITICAL'},
  {id: 'C015', name: 'Epilepsy / Seizure Disorder', specialty: 'SP003', urgency: 'URGENT'},
  {id: 'C016', name: 'Migraine', specialty: 'SP003', urgency: 'ROUTINE'},
  {id: 'C017', name: 'Tension Headache', specialty: 'SP002', urgency: 'ROUTINE'},
  {id: 'C018', name: 'Cerebral Malaria', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C019', name: 'Bell\'s Palsy', specialty: 'SP003', urgency: 'URGENT'},
  {id: 'C020', name: 'Multiple Sclerosis', specialty: 'SP003', urgency: 'ROUTINE'},
  {id: 'C021', name: 'Parkinson\'s Disease', specialty: 'SP003', urgency: 'ROUTINE'},
  {id: 'C022', name: 'Cerebral Abscess', specialty: 'SP003', urgency: 'CRITICAL'},
  {id: 'C023', name: 'Subarachnoid Hemorrhage', specialty: 'SP003', urgency: 'CRITICAL'},
  {id: 'C024', name: 'Tetanus', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C025', name: 'Rabies', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C026', name: 'Malaria (Uncomplicated)', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C027', name: 'Typhoid Fever', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C028', name: 'Cholera', specialty: 'SP006', urgency: 'CRITICAL'},
  {id: 'C029', name: 'Dengue Fever', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C030', name: 'Lassa Fever', specialty: 'SP006', urgency: 'CRITICAL'},
  {id: 'C031', name: 'Yellow Fever', specialty: 'SP006', urgency: 'CRITICAL'},
  {id: 'C032', name: 'Meningococcal Disease', specialty: 'SP006', urgency: 'CRITICAL'},
  {id: 'C033', name: 'Tuberculosis (Pulmonary)', specialty: 'SP004', urgency: 'URGENT'},
  {id: 'C034', name: 'HIV/AIDS (New Presentation)', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C035', name: 'Hepatitis B', specialty: 'SP005', urgency: 'URGENT'},
  {id: 'C036', name: 'Hepatitis A', specialty: 'SP005', urgency: 'URGENT'},
  {id: 'C037', name: 'Brucellosis', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C038', name: 'Influenza', specialty: 'SP002', urgency: 'ROUTINE'},
  {id: 'C039', name: 'COVID-19', specialty: 'SP004', urgency: 'URGENT'},
  {id: 'C040', name: 'Sepsis', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C041', name: 'Ebola Virus Disease', specialty: 'SP006', urgency: 'CRITICAL'},
  {id: 'C042', name: 'Monkeypox', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C043', name: 'Measles', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C044', name: 'Chickenpox (Varicella)', specialty: 'SP006', urgency: 'ROUTINE'},
  {id: 'C045', name: 'Mumps', specialty: 'SP006', urgency: 'ROUTINE'},
  {id: 'C046', name: 'Whooping Cough (Pertussis)', specialty: 'SP014', urgency: 'URGENT'},
  {id: 'C047', name: 'Schistosomiasis', specialty: 'SP006', urgency: 'ROUTINE'},
  {id: 'C048', name: 'Onchocerciasis (River Blindness)', specialty: 'SP011', urgency: 'URGENT'},
  {id: 'C049', name: 'Lymphatic Filariasis', specialty: 'SP006', urgency: 'ROUTINE'},
  {id: 'C050', name: 'Trypanosomiasis (Sleeping Sickness)', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C051', name: 'Leishmaniasis', specialty: 'SP006', urgency: 'ROUTINE'},
  {id: 'C052', name: 'Diphtheria', specialty: 'SP006', urgency: 'CRITICAL'},
  {id: 'C053', name: 'Poliomyelitis', specialty: 'SP014', urgency: 'URGENT'},
  {id: 'C054', name: 'Typhus Fever', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C055', name: 'Viral Hemorrhagic Fever', specialty: 'SP006', urgency: 'CRITICAL'},
  {id: 'C056', name: 'Pneumonia (Community-Acquired)', specialty: 'SP004', urgency: 'URGENT'},
  {id: 'C057', name: 'Asthma (Acute Exacerbation)', specialty: 'SP004', urgency: 'URGENT'},
  {id: 'C058', name: 'Chronic Obstructive Pulmonary Disease (COPD)', specialty: 'SP004', urgency: 'URGENT'},
  {id: 'C059', name: 'Bronchitis (Acute)', specialty: 'SP002', urgency: 'ROUTINE'},
  {id: 'C060', name: 'Pleural Effusion', specialty: 'SP004', urgency: 'URGENT'},
  {id: 'C061', name: 'Pneumothorax', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C062', name: 'Upper Respiratory Tract Infection', specialty: 'SP002', urgency: 'ROUTINE'},
  {id: 'C063', name: 'Sinusitis', specialty: 'SP012', urgency: 'ROUTINE'},
  {id: 'C064', name: 'Allergic Rhinitis', specialty: 'SP012', urgency: 'ROUTINE'},
  {id: 'C065', name: 'Laryngitis', specialty: 'SP012', urgency: 'ROUTINE'},
  {id: 'C066', name: 'Lung Abscess', specialty: 'SP004', urgency: 'URGENT'},
  {id: 'C067', name: 'Pulmonary Hypertension', specialty: 'SP004', urgency: 'URGENT'},
  {id: 'C068', name: 'Sleep Apnea', specialty: 'SP004', urgency: 'ROUTINE'},
  {id: 'C069', name: 'Bronchiectasis', specialty: 'SP004', urgency: 'URGENT'},
  {id: 'C070', name: 'Pharyngitis / Tonsillitis', specialty: 'SP012', urgency: 'ROUTINE'},
  {id: 'C071', name: 'Acute Appendicitis', specialty: 'SP021', urgency: 'CRITICAL'},
  {id: 'C072', name: 'Peptic Ulcer Disease', specialty: 'SP005', urgency: 'URGENT'},
  {id: 'C073', name: 'Acute Gastroenteritis', specialty: 'SP002', urgency: 'ROUTINE'},
  {id: 'C074', name: 'Irritable Bowel Syndrome', specialty: 'SP005', urgency: 'ROUTINE'},
  {id: 'C075', name: 'Liver Cirrhosis', specialty: 'SP005', urgency: 'URGENT'},
  {id: 'C076', name: 'Acute Pancreatitis', specialty: 'SP005', urgency: 'CRITICAL'},
  {id: 'C077', name: 'Intestinal Obstruction', specialty: 'SP021', urgency: 'CRITICAL'},
  {id: 'C078', name: 'Inguinal Hernia', specialty: 'SP021', urgency: 'ROUTINE'},
  {id: 'C079', name: 'Hemorrhoids', specialty: 'SP005', urgency: 'ROUTINE'},
  {id: 'C080', name: 'Anal Fissure', specialty: 'SP005', urgency: 'ROUTINE'},
  {id: 'C081', name: 'Gastroesophageal Reflux Disease (GERD)', specialty: 'SP005', urgency: 'ROUTINE'},
  {id: 'C082', name: 'Acute Liver Failure', specialty: 'SP005', urgency: 'CRITICAL'},
  {id: 'C083', name: 'Colorectal Cancer (Suspected)', specialty: 'SP018', urgency: 'URGENT'},
  {id: 'C084', name: 'Inflammatory Bowel Disease (Crohn\'s / Ulcerative Colitis)', specialty: 'SP005', urgency: 'URGENT'},
  {id: 'C085', name: 'Intestinal Parasites (Worm Infestation)', specialty: 'SP002', urgency: 'ROUTINE'},
  {id: 'C086', name: 'Food Poisoning', specialty: 'SP002', urgency: 'ROUTINE'},
  {id: 'C087', name: 'Gastric Outlet Obstruction', specialty: 'SP005', urgency: 'URGENT'},
  {id: 'C088', name: 'Rectal Prolapse', specialty: 'SP021', urgency: 'URGENT'},
  {id: 'C089', name: 'Diverticulitis', specialty: 'SP005', urgency: 'URGENT'},
  {id: 'C090', name: 'Mesenteric Ischemia', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C091', name: 'Urinary Tract Infection (UTI)', specialty: 'SP016', urgency: 'ROUTINE'},
  {id: 'C092', name: 'Kidney Stones (Nephrolithiasis)', specialty: 'SP007', urgency: 'URGENT'},
  {id: 'C093', name: 'Acute Kidney Injury', specialty: 'SP007', urgency: 'CRITICAL'},
  {id: 'C094', name: 'Chronic Kidney Disease', specialty: 'SP007', urgency: 'URGENT'},
  {id: 'C095', name: 'Nephrotic Syndrome', specialty: 'SP007', urgency: 'URGENT'},
  {id: 'C096', name: 'Pyelonephritis', specialty: 'SP007', urgency: 'URGENT'},
  {id: 'C097', name: 'Benign Prostatic Hyperplasia (BPH)', specialty: 'SP016', urgency: 'ROUTINE'},
  {id: 'C098', name: 'Prostate Cancer (Suspected)', specialty: 'SP016', urgency: 'URGENT'},
  {id: 'C099', name: 'Testicular Torsion', specialty: 'SP016', urgency: 'CRITICAL'},
  {id: 'C100', name: 'Epididymo-Orchitis', specialty: 'SP016', urgency: 'URGENT'},
  {id: 'C101', name: 'Urethral Stricture', specialty: 'SP016', urgency: 'ROUTINE'},
  {id: 'C102', name: 'Bladder Infection (Cystitis)', specialty: 'SP016', urgency: 'ROUTINE'},
  {id: 'C103', name: 'Type 2 Diabetes Mellitus', specialty: 'SP008', urgency: 'ROUTINE'},
  {id: 'C104', name: 'Diabetic Ketoacidosis (DKA)', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C105', name: 'Hypoglycemia (Low Blood Sugar)', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C106', name: 'Hyperthyroidism', specialty: 'SP008', urgency: 'ROUTINE'},
  {id: 'C107', name: 'Hypothyroidism', specialty: 'SP008', urgency: 'ROUTINE'},
  {id: 'C108', name: 'Thyroid Storm', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C109', name: 'Addison\'s Disease (Adrenal Crisis)', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C110', name: 'Cushing\'s Syndrome', specialty: 'SP008', urgency: 'ROUTINE'},
  {id: 'C111', name: 'Hyponatremia (Low Sodium)', specialty: 'SP020', urgency: 'URGENT'},
  {id: 'C112', name: 'Hyperkalemia', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C113', name: 'Gout', specialty: 'SP019', urgency: 'ROUTINE'},
  {id: 'C114', name: 'Metabolic Syndrome', specialty: 'SP008', urgency: 'ROUTINE'},
  {id: 'C115', name: 'Sickle Cell Crisis (Vaso-Occlusive)', specialty: 'SP017', urgency: 'CRITICAL'},
  {id: 'C116', name: 'Severe Anemia', specialty: 'SP017', urgency: 'URGENT'},
  {id: 'C117', name: 'Leukemia (Suspected)', specialty: 'SP017', urgency: 'URGENT'},
  {id: 'C118', name: 'Lymphoma (Suspected)', specialty: 'SP017', urgency: 'URGENT'},
  {id: 'C119', name: 'Hemophilia', specialty: 'SP017', urgency: 'URGENT'},
  {id: 'C120', name: 'Thrombocytopenia (Low Platelets)', specialty: 'SP017', urgency: 'URGENT'},
  {id: 'C121', name: 'Deep Vein Thrombosis', specialty: 'SP001', urgency: 'URGENT'},
  {id: 'C122', name: 'Iron Deficiency Anemia', specialty: 'SP017', urgency: 'ROUTINE'},
  {id: 'C123', name: 'G6PD Deficiency Crisis', specialty: 'SP017', urgency: 'URGENT'},
  {id: 'C124', name: 'Polycythemia', specialty: 'SP017', urgency: 'ROUTINE'},
  {id: 'C125', name: 'Pre-Eclampsia', specialty: 'SP013', urgency: 'CRITICAL'},
  {id: 'C126', name: 'Eclampsia', specialty: 'SP013', urgency: 'CRITICAL'},
  {id: 'C127', name: 'Ectopic Pregnancy', specialty: 'SP013', urgency: 'CRITICAL'},
  {id: 'C128', name: 'Placenta Previa', specialty: 'SP013', urgency: 'CRITICAL'},
  {id: 'C129', name: 'Postpartum Hemorrhage', specialty: 'SP013', urgency: 'CRITICAL'},
  {id: 'C130', name: 'Pelvic Inflammatory Disease (PID)', specialty: 'SP013', urgency: 'URGENT'},
  {id: 'C131', name: 'Ovarian Cyst (Ruptured)', specialty: 'SP013', urgency: 'CRITICAL'},
  {id: 'C132', name: 'Uterine Fibroid', specialty: 'SP013', urgency: 'ROUTINE'},
  {id: 'C133', name: 'Endometriosis', specialty: 'SP013', urgency: 'ROUTINE'},
  {id: 'C134', name: 'Cervical Cancer (Suspected)', specialty: 'SP018', urgency: 'URGENT'},
  {id: 'C135', name: 'Breast Cancer (Suspected)', specialty: 'SP018', urgency: 'URGENT'},
  {id: 'C136', name: 'Dysmenorrhea (Painful Periods)', specialty: 'SP013', urgency: 'ROUTINE'},
  {id: 'C137', name: 'Miscarriage / Threatened Abortion', specialty: 'SP013', urgency: 'URGENT'},
  {id: 'C138', name: 'Puerperal Sepsis', specialty: 'SP013', urgency: 'CRITICAL'},
  {id: 'C139', name: 'Fracture (Closed)', specialty: 'SP009', urgency: 'URGENT'},
  {id: 'C140', name: 'Septic Arthritis', specialty: 'SP009', urgency: 'URGENT'},
  {id: 'C141', name: 'Osteomyelitis', specialty: 'SP009', urgency: 'URGENT'},
  {id: 'C142', name: 'Rheumatoid Arthritis', specialty: 'SP019', urgency: 'ROUTINE'},
  {id: 'C143', name: 'Osteoarthritis', specialty: 'SP009', urgency: 'ROUTINE'},
  {id: 'C144', name: 'Ankylosing Spondylitis', specialty: 'SP019', urgency: 'ROUTINE'},
  {id: 'C145', name: 'Spinal Cord Compression', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C146', name: 'Slipped Disc (Herniated Nucleus Pulposus)', specialty: 'SP009', urgency: 'URGENT'},
  {id: 'C147', name: 'Acute Low Back Pain', specialty: 'SP009', urgency: 'ROUTINE'},
  {id: 'C148', name: 'Compartment Syndrome', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C149', name: 'Avascular Necrosis', specialty: 'SP009', urgency: 'URGENT'},
  {id: 'C150', name: 'Reactive Arthritis', specialty: 'SP019', urgency: 'ROUTINE'},
  {id: 'C151', name: 'Tinea (Fungal Skin Infection)', specialty: 'SP010', urgency: 'ROUTINE'},
  {id: 'C152', name: 'Scabies', specialty: 'SP010', urgency: 'ROUTINE'},
  {id: 'C153', name: 'Cellulitis', specialty: 'SP010', urgency: 'URGENT'},
  {id: 'C154', name: 'Abscess / Boil (Furuncle)', specialty: 'SP010', urgency: 'ROUTINE'},
  {id: 'C155', name: 'Psoriasis', specialty: 'SP010', urgency: 'ROUTINE'},
  {id: 'C156', name: 'Eczema (Atopic Dermatitis)', specialty: 'SP010', urgency: 'ROUTINE'},
  {id: 'C157', name: 'Urticaria (Hives)', specialty: 'SP010', urgency: 'ROUTINE'},
  {id: 'C158', name: 'Herpes Zoster (Shingles)', specialty: 'SP010', urgency: 'URGENT'},
  {id: 'C159', name: 'Diabetic Foot Ulcer', specialty: 'SP008', urgency: 'URGENT'},
  {id: 'C160', name: 'Burns (Severe)', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C161', name: 'Contact Dermatitis', specialty: 'SP010', urgency: 'ROUTINE'},
  {id: 'C162', name: 'Impetigo', specialty: 'SP010', urgency: 'ROUTINE'},
  {id: 'C163', name: 'Gonorrhea', specialty: 'SP016', urgency: 'ROUTINE'},
  {id: 'C164', name: 'Syphilis', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C165', name: 'Chlamydia', specialty: 'SP006', urgency: 'ROUTINE'},
  {id: 'C166', name: 'Genital Herpes', specialty: 'SP010', urgency: 'ROUTINE'},
  {id: 'C167', name: 'Trichomoniasis', specialty: 'SP013', urgency: 'ROUTINE'},
  {id: 'C168', name: 'HPV Infection', specialty: 'SP013', urgency: 'ROUTINE'},
  {id: 'C169', name: 'Chancroid', specialty: 'SP006', urgency: 'URGENT'},
  {id: 'C170', name: 'Pelvic Inflammatory Disease (STI-related)', specialty: 'SP013', urgency: 'URGENT'},
  {id: 'C171', name: 'Conjunctivitis (Bacterial / Viral)', specialty: 'SP011', urgency: 'ROUTINE'},
  {id: 'C172', name: 'Glaucoma (Acute Angle Closure)', specialty: 'SP011', urgency: 'CRITICAL'},
  {id: 'C173', name: 'Retinal Detachment', specialty: 'SP011', urgency: 'CRITICAL'},
  {id: 'C174', name: 'Uveitis', specialty: 'SP011', urgency: 'URGENT'},
  {id: 'C175', name: 'Corneal Ulcer', specialty: 'SP011', urgency: 'URGENT'},
  {id: 'C176', name: 'Cataracts', specialty: 'SP011', urgency: 'ROUTINE'},
  {id: 'C177', name: 'Orbital Cellulitis', specialty: 'SP011', urgency: 'URGENT'},
  {id: 'C178', name: 'Acute Otitis Media (Ear Infection)', specialty: 'SP012', urgency: 'ROUTINE'},
  {id: 'C179', name: 'Chronic Suppurative Otitis Media', specialty: 'SP012', urgency: 'ROUTINE'},
  {id: 'C180', name: 'Mastoiditis', specialty: 'SP012', urgency: 'URGENT'},
  {id: 'C181', name: 'Peritonsillar Abscess', specialty: 'SP012', urgency: 'URGENT'},
  {id: 'C182', name: 'Epiglottitis', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C183', name: 'Nasal Polyps', specialty: 'SP012', urgency: 'ROUTINE'},
  {id: 'C184', name: 'Ear Foreign Body', specialty: 'SP012', urgency: 'ROUTINE'},
  {id: 'C185', name: 'Vocal Cord Polyp', specialty: 'SP012', urgency: 'ROUTINE'},
  {id: 'C186', name: 'Major Depressive Disorder', specialty: 'SP015', urgency: 'ROUTINE'},
  {id: 'C187', name: 'Generalized Anxiety Disorder', specialty: 'SP015', urgency: 'ROUTINE'},
  {id: 'C188', name: 'Schizophrenia', specialty: 'SP015', urgency: 'URGENT'},
  {id: 'C189', name: 'Bipolar Disorder', specialty: 'SP015', urgency: 'ROUTINE'},
  {id: 'C190', name: 'Acute Suicidal Crisis', specialty: 'SP015', urgency: 'CRITICAL'},
  {id: 'C191', name: 'Substance Use Disorder', specialty: 'SP015', urgency: 'URGENT'},
  {id: 'C192', name: 'Post-Traumatic Stress Disorder (PTSD)', specialty: 'SP015', urgency: 'ROUTINE'},
  {id: 'C193', name: 'Acute Psychosis', specialty: 'SP015', urgency: 'CRITICAL'},
  {id: 'C194', name: 'Snakebite Envenomation', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C195', name: 'Severe Burns', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C196', name: 'Traumatic Brain Injury', specialty: 'SP003', urgency: 'CRITICAL'},
  {id: 'C197', name: 'Anaphylaxis', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C198', name: 'Drowning / Near-Drowning', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C199', name: 'Heat Stroke', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C200', name: 'Acute Poisoning / Overdose', specialty: 'SP020', urgency: 'CRITICAL'},
  {id: 'C201', name: 'Dental Caries / Tooth Decay', specialty: 'SP022', urgency: 'ROUTINE'},
  {id: 'C202', name: 'Dental Abscess', specialty: 'SP022', urgency: 'URGENT'}
] AS row
MERGE (c:Condition {id: row.id})
SET c.name = row.name
WITH row, c
MATCH (sp:Specialty {id: row.specialty})
MERGE (c)-[:ROUTES_TO]->(sp)
WITH row, c
MATCH (u:Urgency {level: row.urgency})
MERGE (c)-[:HAS_SEVERITY]->(u);

UNWIND [
  {symptom: 'S001', condition: 'C001', weight: 95}, {symptom: 'S002', condition: 'C001', weight: 88}, {symptom: 'S008', condition: 'C001', weight: 82}, {symptom: 'S007', condition: 'C001', weight: 75}, {symptom: 'S021', condition: 'C001', weight: 60},
  {symptom: 'S009', condition: 'C002', weight: 90}, {symptom: 'S017', condition: 'C002', weight: 78}, {symptom: 'S005', condition: 'C002', weight: 72}, {symptom: 'S001', condition: 'C002', weight: 65}, {symptom: 'S026', condition: 'C002', weight: 55},
  {symptom: 'S002', condition: 'C003', weight: 90}, {symptom: 'S004', condition: 'C003', weight: 88}, {symptom: 'S023', condition: 'C003', weight: 75}, {symptom: 'S041', condition: 'C003', weight: 70},
  {symptom: 'S003', condition: 'C004', weight: 92}, {symptom: 'S006', condition: 'C004', weight: 80}, {symptom: 'S005', condition: 'C004', weight: 70},
  {symptom: 'S001', condition: 'C005', weight: 88}, {symptom: 'S002', condition: 'C005', weight: 72}, {symptom: 'S023', condition: 'C005', weight: 60},
  {symptom: 'S001', condition: 'C006', weight: 80}, {symptom: 'S019', condition: 'C006', weight: 70}, {symptom: 'S022', condition: 'C006', weight: 60},
  {symptom: 'S019', condition: 'C007', weight: 80}, {symptom: 'S003', condition: 'C007', weight: 72},
  {symptom: 'S001', condition: 'C008', weight: 95}, {symptom: 'S047', condition: 'C008', weight: 85}, {symptom: 'S002', condition: 'C008', weight: 78},
  {symptom: 'S004', condition: 'C009', weight: 85}, {symptom: 'S072', condition: 'C009', weight: 75},
  {symptom: 'S002', condition: 'C010', weight: 92}, {symptom: 'S001', condition: 'C010', weight: 85}, {symptom: 'S040', condition: 'C010', weight: 75},
  {symptom: 'S011', condition: 'C011', weight: 95}, {symptom: 'S013', condition: 'C011', weight: 92}, {symptom: 'S012', condition: 'C011', weight: 90}, {symptom: 'S010', condition: 'C011', weight: 85}, {symptom: 'S009', condition: 'C011', weight: 70},
  {symptom: 'S009', condition: 'C012', weight: 95}, {symptom: 'S018', condition: 'C012', weight: 90}, {symptom: 'S026', condition: 'C012', weight: 75},
  {symptom: 'S011', condition: 'C013', weight: 85}, {symptom: 'S013', condition: 'C013', weight: 80}, {symptom: 'S016', condition: 'C013', weight: 72},
  {symptom: 'S111', condition: 'C014', weight: 95}, {symptom: 'S009', condition: 'C014', weight: 92}, {symptom: 'S019', condition: 'C014', weight: 88}, {symptom: 'S112', condition: 'C014', weight: 80}, {symptom: 'S026', condition: 'C014', weight: 70},
  {symptom: 'S014', condition: 'C015', weight: 98}, {symptom: 'S018', condition: 'C015', weight: 80}, {symptom: 'S015', condition: 'C015', weight: 60},
  {symptom: 'S009', condition: 'C016', weight: 88}, {symptom: 'S112', condition: 'C016', weight: 80}, {symptom: 'S026', condition: 'C016', weight: 72}, {symptom: 'S017', condition: 'C016', weight: 65},
  {symptom: 'S009', condition: 'C017', weight: 82}, {symptom: 'S023', condition: 'C017', weight: 55},
  {symptom: 'S019', condition: 'C018', weight: 88}, {symptom: 'S014', condition: 'C018', weight: 85}, {symptom: 'S010', condition: 'C018', weight: 82}, {symptom: 'S018', condition: 'C018', weight: 78},
  {symptom: 'S011', condition: 'C019', weight: 88}, {symptom: 'S016', condition: 'C020', weight: 72}, {symptom: 'S015', condition: 'C021', weight: 65}, {symptom: 'S009', condition: 'C022', weight: 80}, {symptom: 'S009', condition: 'C023', weight: 95}, {symptom: 'S111', condition: 'C023', weight: 90}, {symptom: 'S074', condition: 'C024', weight: 85}, {symptom: 'S111', condition: 'C024', weight: 88},
  {symptom: 'S019', condition: 'C026', weight: 90}, {symptom: 'S020', condition: 'C026', weight: 88}, {symptom: 'S022', condition: 'C026', weight: 82}, {symptom: 'S009', condition: 'C026', weight: 75}, {symptom: 'S025', condition: 'C026', weight: 70}, {symptom: 'S021', condition: 'C026', weight: 65},
  {symptom: 'S019', condition: 'C027', weight: 88}, {symptom: 'S030', condition: 'C027', weight: 80}, {symptom: 'S028', condition: 'C027', weight: 75}, {symptom: 'S024', condition: 'C027', weight: 70}, {symptom: 'S009', condition: 'C027', weight: 65},
  {symptom: 'S028', condition: 'C028', weight: 95}, {symptom: 'S026', condition: 'C028', weight: 90}, {symptom: 'S023', condition: 'C028', weight: 80},
  {symptom: 'S019', condition: 'C029', weight: 88}, {symptom: 'S027', condition: 'C029', weight: 85}, {symptom: 'S051', condition: 'C029', weight: 78}, {symptom: 'S009', condition: 'C029', weight: 72},
  {symptom: 'S019', condition: 'C030', weight: 88}, {symptom: 'S062', condition: 'C030', weight: 85}, {symptom: 'S022', condition: 'C030', weight: 80}, {symptom: 'S040', condition: 'C030', weight: 75},
  {symptom: 'S019', condition: 'C031', weight: 85}, {symptom: 'S036', condition: 'C031', weight: 82}, {symptom: 'S040', condition: 'C031', weight: 78},
  {symptom: 'S111', condition: 'C032', weight: 86}, {symptom: 'S019', condition: 'C032', weight: 84}, {symptom: 'S113', condition: 'C032', weight: 76},
  {symptom: 'S039', condition: 'C033', weight: 90}, {symptom: 'S040', condition: 'C033', weight: 88}, {symptom: 'S043', condition: 'C033', weight: 85}, {symptom: 'S042', condition: 'C033', weight: 80}, {symptom: 'S019', condition: 'C033', weight: 72},
  {symptom: 'S106', condition: 'C034', weight: 80}, {symptom: 'S043', condition: 'C034', weight: 78}, {symptom: 'S038', condition: 'C034', weight: 65}, {symptom: 'S028', condition: 'C034', weight: 60},
  {symptom: 'S036', condition: 'C035', weight: 90}, {symptom: 'S119', condition: 'C035', weight: 82}, {symptom: 'S030', condition: 'C035', weight: 75}, {symptom: 'S023', condition: 'C035', weight: 70},
  {symptom: 'S036', condition: 'C036', weight: 88}, {symptom: 'S025', condition: 'C036', weight: 78}, {symptom: 'S037', condition: 'C036', weight: 72},
  {symptom: 'S019', condition: 'C038', weight: 82}, {symptom: 'S022', condition: 'C038', weight: 80}, {symptom: 'S038', condition: 'C038', weight: 78}, {symptom: 'S009', condition: 'C038', weight: 70}, {symptom: 'S066', condition: 'C038', weight: 65},
  {symptom: 'S038', condition: 'C039', weight: 85}, {symptom: 'S019', condition: 'C039', weight: 82}, {symptom: 'S002', condition: 'C039', weight: 80}, {symptom: 'S023', condition: 'C039', weight: 72},
  {symptom: 'S019', condition: 'C040', weight: 88}, {symptom: 'S010', condition: 'C040', weight: 82}, {symptom: 'S002', condition: 'C040', weight: 80}, {symptom: 'S005', condition: 'C040', weight: 75},
  {symptom: 'S051', condition: 'C042', weight: 88}, {symptom: 'S019', condition: 'C042', weight: 80}, {symptom: 'S106', condition: 'C042', weight: 72},
  {symptom: 'S113', condition: 'C043', weight: 92}, {symptom: 'S057', condition: 'C043', weight: 80}, {symptom: 'S066', condition: 'C043', weight: 75}, {symptom: 'S085', condition: 'C043', weight: 80},
  {symptom: 'S051', condition: 'C044', weight: 88}, {symptom: 'S052', condition: 'C044', weight: 82}, {symptom: 'S019', condition: 'C044', weight: 75},
  {symptom: 'S002', condition: 'C052', weight: 82}, {symptom: 'S070', condition: 'C052', weight: 80}, {symptom: 'S019', condition: 'C055', weight: 85}, {symptom: 'S040', condition: 'C055', weight: 80},
  {symptom: 'S039', condition: 'C056', weight: 90}, {symptom: 'S019', condition: 'C056', weight: 85}, {symptom: 'S002', condition: 'C056', weight: 80}, {symptom: 'S001', condition: 'C056', weight: 72},
  {symptom: 'S041', condition: 'C057', weight: 92}, {symptom: 'S002', condition: 'C057', weight: 88}, {symptom: 'S038', condition: 'C057', weight: 75},
  {symptom: 'S002', condition: 'C058', weight: 88}, {symptom: 'S039', condition: 'C058', weight: 85}, {symptom: 'S041', condition: 'C058', weight: 80},
  {symptom: 'S038', condition: 'C059', weight: 85}, {symptom: 'S039', condition: 'C059', weight: 82}, {symptom: 'S019', condition: 'C059', weight: 65},
  {symptom: 'S002', condition: 'C060', weight: 85}, {symptom: 'S001', condition: 'C060', weight: 75},
  {symptom: 'S001', condition: 'C061', weight: 90}, {symptom: 'S002', condition: 'C061', weight: 88},
  {symptom: 'S066', condition: 'C062', weight: 80}, {symptom: 'S068', condition: 'C062', weight: 75}, {symptom: 'S062', condition: 'C062', weight: 72}, {symptom: 'S019', condition: 'C062', weight: 65},
  {symptom: 'S067', condition: 'C063', weight: 85}, {symptom: 'S009', condition: 'C063', weight: 72},
  {symptom: 'S068', condition: 'C064', weight: 85}, {symptom: 'S066', condition: 'C064', weight: 82}, {symptom: 'S052', condition: 'C064', weight: 70},
  {symptom: 'S069', condition: 'C065', weight: 90}, {symptom: 'S062', condition: 'C065', weight: 72},
  {symptom: 'S062', condition: 'C070', weight: 90}, {symptom: 'S019', condition: 'C070', weight: 75}, {symptom: 'S070', condition: 'C070', weight: 70},
  {symptom: 'S031', condition: 'C071', weight: 95}, {symptom: 'S019', condition: 'C071', weight: 80}, {symptom: 'S026', condition: 'C071', weight: 72},
  {symptom: 'S034', condition: 'C072', weight: 88}, {symptom: 'S030', condition: 'C072', weight: 82}, {symptom: 'S025', condition: 'C072', weight: 70}, {symptom: 'S035', condition: 'C072', weight: 65},
  {symptom: 'S028', condition: 'C073', weight: 88}, {symptom: 'S026', condition: 'C073', weight: 85}, {symptom: 'S030', condition: 'C073', weight: 78}, {symptom: 'S019', condition: 'C073', weight: 65},
  {symptom: 'S030', condition: 'C074', weight: 82}, {symptom: 'S032', condition: 'C074', weight: 80}, {symptom: 'S028', condition: 'C074', weight: 72},
  {symptom: 'S036', condition: 'C075', weight: 88}, {symptom: 'S032', condition: 'C075', weight: 80}, {symptom: 'S004', condition: 'C075', weight: 75}, {symptom: 'S043', condition: 'C075', weight: 70},
  {symptom: 'S030', condition: 'C076', weight: 92}, {symptom: 'S026', condition: 'C076', weight: 82}, {symptom: 'S019', condition: 'C076', weight: 72},
  {symptom: 'S030', condition: 'C077', weight: 90}, {symptom: 'S033', condition: 'C077', weight: 80}, {symptom: 'S026', condition: 'C077', weight: 74},
  {symptom: 'S030', condition: 'C078', weight: 78}, {symptom: 'S032', condition: 'C078', weight: 72}, {symptom: 'S029', condition: 'C079', weight: 85}, {symptom: 'S033', condition: 'C079', weight: 72}, {symptom: 'S034', condition: 'C081', weight: 90},
  {symptom: 'S036', condition: 'C082', weight: 88}, {symptom: 'S010', condition: 'C082', weight: 80}, {symptom: 'S029', condition: 'C084', weight: 85}, {symptom: 'S030', condition: 'C084', weight: 80}, {symptom: 'S043', condition: 'C084', weight: 72},
  {symptom: 'S030', condition: 'C085', weight: 80}, {symptom: 'S028', condition: 'C085', weight: 75}, {symptom: 'S043', condition: 'C085', weight: 65}, {symptom: 'S026', condition: 'C086', weight: 88}, {symptom: 'S028', condition: 'C086', weight: 85}, {symptom: 'S030', condition: 'C086', weight: 78},
  {symptom: 'S044', condition: 'C091', weight: 92}, {symptom: 'S045', condition: 'C091', weight: 85}, {symptom: 'S019', condition: 'C091', weight: 70},
  {symptom: 'S049', condition: 'C092', weight: 92}, {symptom: 'S046', condition: 'C092', weight: 82}, {symptom: 'S025', condition: 'C092', weight: 70},
  {symptom: 'S048', condition: 'C093', weight: 88}, {symptom: 'S004', condition: 'C093', weight: 80}, {symptom: 'S010', condition: 'C093', weight: 72},
  {symptom: 'S050', condition: 'C094', weight: 82}, {symptom: 'S004', condition: 'C094', weight: 78}, {symptom: 'S023', condition: 'C094', weight: 72},
  {symptom: 'S050', condition: 'C095', weight: 88}, {symptom: 'S004', condition: 'C095', weight: 85}, {symptom: 'S120', condition: 'C095', weight: 75},
  {symptom: 'S049', condition: 'C096', weight: 88}, {symptom: 'S019', condition: 'C096', weight: 82}, {symptom: 'S044', condition: 'C096', weight: 75},
  {symptom: 'S048', condition: 'C097', weight: 85}, {symptom: 'S118', condition: 'C097', weight: 80}, {symptom: 'S045', condition: 'C097', weight: 75},
  {symptom: 'S118', condition: 'C098', weight: 78}, {symptom: 'S048', condition: 'C098', weight: 72}, {symptom: 'S047', condition: 'C098', weight: 65},
  {symptom: 'S079', condition: 'C099', weight: 92}, {symptom: 'S026', condition: 'C099', weight: 72},
  {symptom: 'S044', condition: 'C100', weight: 82}, {symptom: 'S079', condition: 'C100', weight: 76}, {symptom: 'S044', condition: 'C102', weight: 85},
  {symptom: 'S094', condition: 'C103', weight: 88}, {symptom: 'S045', condition: 'C103', weight: 82}, {symptom: 'S023', condition: 'C103', weight: 75}, {symptom: 'S054', condition: 'C103', weight: 70},
  {symptom: 'S094', condition: 'C104', weight: 85}, {symptom: 'S026', condition: 'C104', weight: 82}, {symptom: 'S002', condition: 'C104', weight: 80}, {symptom: 'S010', condition: 'C104', weight: 75},
  {symptom: 'S100', condition: 'C105', weight: 92}, {symptom: 'S010', condition: 'C105', weight: 82}, {symptom: 'S006', condition: 'C105', weight: 75},
  {symptom: 'S003', condition: 'C106', weight: 80}, {symptom: 'S097', condition: 'C106', weight: 78}, {symptom: 'S096', condition: 'C106', weight: 72}, {symptom: 'S043', condition: 'C106', weight: 65},
  {symptom: 'S023', condition: 'C107', weight: 80}, {symptom: 'S098', condition: 'C107', weight: 75}, {symptom: 'S120', condition: 'C107', weight: 70},
  {symptom: 'S003', condition: 'C108', weight: 88}, {symptom: 'S019', condition: 'C108', weight: 85}, {symptom: 'S010', condition: 'C108', weight: 80},
  {symptom: 'S120', condition: 'C110', weight: 80}, {symptom: 'S056', condition: 'C110', weight: 72}, {symptom: 'S071', condition: 'C113', weight: 90}, {symptom: 'S027', condition: 'C113', weight: 82},
  {symptom: 'S094', condition: 'C114', weight: 75}, {symptom: 'S023', condition: 'C114', weight: 65},
  {symptom: 'S072', condition: 'C115', weight: 92}, {symptom: 'S104', condition: 'C115', weight: 90}, {symptom: 'S105', condition: 'C115', weight: 85}, {symptom: 'S019', condition: 'C115', weight: 78},
  {symptom: 'S101', condition: 'C116', weight: 88}, {symptom: 'S023', condition: 'C116', weight: 82}, {symptom: 'S002', condition: 'C116', weight: 75},
  {symptom: 'S106', condition: 'C117', weight: 82}, {symptom: 'S102', condition: 'C117', weight: 80}, {symptom: 'S101', condition: 'C117', weight: 75}, {symptom: 'S019', condition: 'C117', weight: 70},
  {symptom: 'S103', condition: 'C119', weight: 92}, {symptom: 'S102', condition: 'C119', weight: 85}, {symptom: 'S102', condition: 'C120', weight: 88}, {symptom: 'S103', condition: 'C120', weight: 82},
  {symptom: 'S004', condition: 'C121', weight: 85}, {symptom: 'S072', condition: 'C121', weight: 75}, {symptom: 'S101', condition: 'C122', weight: 85}, {symptom: 'S023', condition: 'C122', weight: 78}, {symptom: 'S002', condition: 'C122', weight: 65},
  {symptom: 'S080', condition: 'C125', weight: 95}, {symptom: 'S081', condition: 'C125', weight: 90}, {symptom: 'S009', condition: 'C125', weight: 80},
  {symptom: 'S080', condition: 'C126', weight: 92}, {symptom: 'S014', condition: 'C126', weight: 90}, {symptom: 'S081', condition: 'C126', weight: 85},
  {symptom: 'S079', condition: 'C127', weight: 92}, {symptom: 'S077', condition: 'C127', weight: 85}, {symptom: 'S005', condition: 'C127', weight: 75},
  {symptom: 'S076', condition: 'C128', weight: 84}, {symptom: 'S077', condition: 'C128', weight: 76}, {symptom: 'S076', condition: 'C129', weight: 92}, {symptom: 'S005', condition: 'C129', weight: 80},
  {symptom: 'S079', condition: 'C130', weight: 88}, {symptom: 'S019', condition: 'C130', weight: 78}, {symptom: 'S078', condition: 'C130', weight: 72},
  {symptom: 'S079', condition: 'C131', weight: 90}, {symptom: 'S026', condition: 'C131', weight: 72},
  {symptom: 'S076', condition: 'C132', weight: 85}, {symptom: 'S079', condition: 'C132', weight: 78}, {symptom: 'S082', condition: 'C133', weight: 85}, {symptom: 'S079', condition: 'C133', weight: 80},
  {symptom: 'S076', condition: 'C137', weight: 85}, {symptom: 'S079', condition: 'C137', weight: 80}, {symptom: 'S019', condition: 'C138', weight: 88}, {symptom: 'S079', condition: 'C138', weight: 80},
  {symptom: 'S109', condition: 'C139', weight: 95}, {symptom: 'S075', condition: 'C139', weight: 82},
  {symptom: 'S071', condition: 'C140', weight: 88}, {symptom: 'S019', condition: 'C140', weight: 80}, {symptom: 'S075', condition: 'C140', weight: 75},
  {symptom: 'S072', condition: 'C141', weight: 85}, {symptom: 'S019', condition: 'C141', weight: 78},
  {symptom: 'S027', condition: 'C142', weight: 85}, {symptom: 'S073', condition: 'C142', weight: 80}, {symptom: 'S071', condition: 'C142', weight: 78},
  {symptom: 'S027', condition: 'C143', weight: 82}, {symptom: 'S073', condition: 'C143', weight: 78},
  {symptom: 'S047', condition: 'C146', weight: 88}, {symptom: 'S016', condition: 'C146', weight: 80}, {symptom: 'S047', condition: 'C147', weight: 90}, {symptom: 'S073', condition: 'C147', weight: 75},
  {symptom: 'S052', condition: 'C151', weight: 85}, {symptom: 'S051', condition: 'C151', weight: 80}, {symptom: 'S053', condition: 'C151', weight: 70},
  {symptom: 'S052', condition: 'C152', weight: 90}, {symptom: 'S051', condition: 'C152', weight: 80},
  {symptom: 'S055', condition: 'C153', weight: 85}, {symptom: 'S019', condition: 'C153', weight: 75}, {symptom: 'S051', condition: 'C153', weight: 70},
  {symptom: 'S055', condition: 'C154', weight: 92}, {symptom: 'S019', condition: 'C154', weight: 65},
  {symptom: 'S053', condition: 'C155', weight: 85}, {symptom: 'S052', condition: 'C155', weight: 80},
  {symptom: 'S052', condition: 'C156', weight: 88}, {symptom: 'S051', condition: 'C156', weight: 80}, {symptom: 'S053', condition: 'C156', weight: 72},
  {symptom: 'S052', condition: 'C157', weight: 85}, {symptom: 'S051', condition: 'C157', weight: 82}, {symptom: 'S051', condition: 'C158', weight: 85}, {symptom: 'S052', condition: 'C158', weight: 80}, {symptom: 'S019', condition: 'C158', weight: 65},
  {symptom: 'S054', condition: 'C159', weight: 90}, {symptom: 'S075', condition: 'C159', weight: 75}, {symptom: 'S108', condition: 'C160', weight: 98},
  {symptom: 'S052', condition: 'C161', weight: 85}, {symptom: 'S051', condition: 'C161', weight: 82}, {symptom: 'S051', condition: 'C162', weight: 82}, {symptom: 'S085', condition: 'C162', weight: 75},
  {symptom: 'S115', condition: 'C163', weight: 90}, {symptom: 'S044', condition: 'C163', weight: 78},
  {symptom: 'S114', condition: 'C164', weight: 88}, {symptom: 'S051', condition: 'C164', weight: 70}, {symptom: 'S078', condition: 'C165', weight: 82}, {symptom: 'S044', condition: 'C165', weight: 75},
  {symptom: 'S114', condition: 'C166', weight: 90}, {symptom: 'S044', condition: 'C166', weight: 72}, {symptom: 'S078', condition: 'C167', weight: 85}, {symptom: 'S052', condition: 'C167', weight: 72},
  {symptom: 'S078', condition: 'C170', weight: 82}, {symptom: 'S079', condition: 'C170', weight: 78},
  {symptom: 'S057', condition: 'C171', weight: 88}, {symptom: 'S058', condition: 'C171', weight: 85}, {symptom: 'S052', condition: 'C171', weight: 70},
  {symptom: 'S059', condition: 'C172', weight: 90}, {symptom: 'S017', condition: 'C172', weight: 85}, {symptom: 'S009', condition: 'C172', weight: 75},
  {symptom: 'S060', condition: 'C173', weight: 95}, {symptom: 'S061', condition: 'C173', weight: 88},
  {symptom: 'S059', condition: 'C174', weight: 85}, {symptom: 'S017', condition: 'C174', weight: 78}, {symptom: 'S059', condition: 'C175', weight: 88}, {symptom: 'S058', condition: 'C175', weight: 80},
  {symptom: 'S059', condition: 'C177', weight: 85}, {symptom: 'S019', condition: 'C177', weight: 78},
  {symptom: 'S063', condition: 'C178', weight: 90}, {symptom: 'S019', condition: 'C178', weight: 75}, {symptom: 'S065', condition: 'C178', weight: 68},
  {symptom: 'S064', condition: 'C179', weight: 92}, {symptom: 'S065', condition: 'C179', weight: 80}, {symptom: 'S063', condition: 'C180', weight: 85}, {symptom: 'S019', condition: 'C180', weight: 78},
  {symptom: 'S062', condition: 'C181', weight: 88}, {symptom: 'S070', condition: 'C181', weight: 82}, {symptom: 'S019', condition: 'C181', weight: 75},
  {symptom: 'S070', condition: 'C182', weight: 90}, {symptom: 'S002', condition: 'C182', weight: 85}, {symptom: 'S069', condition: 'C182', weight: 80},
  {symptom: 'S089', condition: 'C186', weight: 90}, {symptom: 'S092', condition: 'C186', weight: 80}, {symptom: 'S023', condition: 'C186', weight: 70},
  {symptom: 'S090', condition: 'C187', weight: 90}, {symptom: 'S092', condition: 'C187', weight: 78}, {symptom: 'S003', condition: 'C187', weight: 65},
  {symptom: 'S091', condition: 'C188', weight: 90}, {symptom: 'S010', condition: 'C188', weight: 75}, {symptom: 'S089', condition: 'C189', weight: 78}, {symptom: 'S092', condition: 'C189', weight: 72},
  {symptom: 'S093', condition: 'C190', weight: 99}, {symptom: 'S089', condition: 'C190', weight: 80}, {symptom: 'S096', condition: 'C191', weight: 75}, {symptom: 'S010', condition: 'C191', weight: 65}, {symptom: 'S091', condition: 'C193', weight: 88}, {symptom: 'S010', condition: 'C193', weight: 80},
  {symptom: 'S107', condition: 'C194', weight: 99}, {symptom: 'S004', condition: 'C194', weight: 80}, {symptom: 'S108', condition: 'C195', weight: 98},
  {symptom: 'S110', condition: 'C196', weight: 95}, {symptom: 'S018', condition: 'C196', weight: 88}, {symptom: 'S026', condition: 'C196', weight: 72},
  {symptom: 'S002', condition: 'C197', weight: 90}, {symptom: 'S052', condition: 'C197', weight: 85}, {symptom: 'S041', condition: 'C197', weight: 80}, {symptom: 'S005', condition: 'C197', weight: 72},
  {symptom: 'S002', condition: 'C198', weight: 90}, {symptom: 'S019', condition: 'C199', weight: 82}, {symptom: 'S010', condition: 'C199', weight: 80}, {symptom: 'S048', condition: 'C199', weight: 72},
  {symptom: 'S026', condition: 'C200', weight: 80}, {symptom: 'S018', condition: 'C200', weight: 78}, {symptom: 'S014', condition: 'C200', weight: 75},
  {symptom: 'S116', condition: 'C201', weight: 90}, {symptom: 'S117', condition: 'C202', weight: 88}, {symptom: 'S116', condition: 'C202', weight: 82},
  {symptom: 'S083', condition: 'C026', weight: 85}, {symptom: 'S083', condition: 'C018', weight: 80}, {symptom: 'S086', condition: 'C028', weight: 82}, {symptom: 'S088', condition: 'C018', weight: 88}, {symptom: 'S088', condition: 'C015', weight: 85}
] AS row
MATCH (s:Symptom {id: row.symptom})
MATCH (c:Condition {id: row.condition})
MERGE (s)-[r:INDICATES]->(c)
SET r.weight = row.weight;

// Verification queries:
// MATCH (c:Condition) RETURN count(c) AS total_conditions; // Expected: 202
// MATCH (s:Symptom) RETURN count(s) AS total_symptoms;     // Expected: 120
// MATCH ()-[r:INDICATES]->() RETURN count(r) AS total_edges;
//
// Triage smoke test:
// MATCH (s:Symptom) WHERE s.id IN ['S001', 'S002']
// MATCH (s)-[r:INDICATES]->(c:Condition)-[:ROUTES_TO]->(sp:Specialty)
// MATCH (c)-[:HAS_SEVERITY]->(u:Urgency)
// RETURN sp.name AS target_specialty, u.level AS derived_urgency, c.id AS condition_id, c.name AS condition_name
// ORDER BY r.weight DESC LIMIT 1;
