export type SignupRole = 'patient' | 'specialist' | 'hospital' | 'clinic' | 'nurse' | 'pharmacy' | 'laboratory' | 'hmo' | 'government' | 'platform-admin';
export type SignupField = { name: string; label: string; type?: 'text' | 'email' | 'tel' | 'password' | 'date' | 'number' | 'textarea' | 'select'; required?: boolean; optional?: boolean; placeholder?: string; options?: string[]; min?: number; max?: number };
export type SignupStep = { title: string; description: string; fields: SignupField[] };
export type SignupConfig = { role: SignupRole; name: string; description: string; access: string; loginPath: string; steps: SignupStep[] };

const identity: SignupField[] = [
  { name: 'first_name', label: 'First name', required: true }, { name: 'middle_name', label: 'Middle name', optional: true }, { name: 'last_name', label: 'Last name', required: true },
  { name: 'phone', label: 'International phone number', type: 'tel', required: true, placeholder: '+234...' }, { name: 'email', label: 'Email address', type: 'email', required: true },
  { name: 'country', label: 'Country', required: true }, { name: 'region', label: 'State, province or region', required: true },
  { name: 'preferred_language', label: 'Preferred language', required: true }, { name: 'time_zone', label: 'Time zone', required: true, placeholder: 'Africa/Lagos' },
];
const security: SignupField[] = [{ name: 'password', label: 'Password', type: 'password', required: true }, { name: 'confirm_password', label: 'Confirm password', type: 'password', required: true }];
const location: SignupField[] = [{ name: 'latitude', label: 'Latitude', type: 'number', required: true, min: -90, max: 90 }, { name: 'longitude', label: 'Longitude', type: 'number', required: true, min: -180, max: 180 }, { name: 'address', label: 'Full address', type: 'textarea', required: true }];
const organizationAdmin: SignupField[] = [{ name: 'administrator_name', label: 'Primary administrator full name', required: true }, { name: 'administrator_title', label: 'Administrator job title', required: true }, { name: 'official_email', label: 'Official work email', type: 'email', required: true }, { name: 'administrator_phone', label: 'Administrator phone', type: 'tel', required: true }, ...security];

export const signupConfigs: Record<SignupRole, SignupConfig> = {
  patient: { role: 'patient', name: 'Patient', description: 'Create a personal account for triage, appointments, queue tracking and your health card.', access: 'Public self-registration. Access begins after phone or email verification.', loginPath: '/login', steps: [
    { title: 'Basic identity', description: 'Tell us who the health record belongs to.', fields: [...identity.filter((field) => !['time_zone'].includes(field.name)), { name: 'date_of_birth', label: 'Date of birth', type: 'date', required: true }, { name: 'gender', label: 'Sex or gender', type: 'select', required: true, options: ['Female', 'Male', 'Other', 'Prefer not to say'] }, { name: 'city', label: 'City or local area', required: true }] },
    { title: 'Account security', description: 'Secure the account before verification.', fields: security },
    { title: 'Emergency and health card', description: 'Medical fields are optional and may be completed later.', fields: [{ name: 'emergency_contact_name', label: 'Emergency contact name', required: true }, { name: 'emergency_contact_relationship', label: 'Relationship', required: true }, { name: 'emergency_contact_phone', label: 'Emergency contact phone', type: 'tel', required: true }, { name: 'blood_group', label: 'Blood group', optional: true }, { name: 'genotype', label: 'Genotype', optional: true }, { name: 'known_allergies', label: 'Known allergies', type: 'textarea', optional: true }, { name: 'current_medications', label: 'Current medications', type: 'textarea', optional: true }, { name: 'medical_conditions', label: 'Existing medical conditions', type: 'textarea', optional: true }, { name: 'hmo_provider', label: 'HMO or insurance provider', optional: true }, { name: 'hmo_member_number', label: 'HMO member number', optional: true }] },
  ] },
  specialist: { role: 'specialist', name: 'Specialist', description: 'Apply as an independent clinician or accept a hospital invitation.', access: 'Pending professional verification and hospital membership approval.', loginPath: '/specialist/login', steps: [
    { title: 'Personal details', description: 'Use the identity on your professional records.', fields: [{ name: 'full_name', label: 'Full legal name', required: true }, ...identity.slice(3)] },
    { title: 'Professional details', description: 'We verify credentials with the stated licensing authority.', fields: [{ name: 'professional_title', label: 'Professional title', required: true }, { name: 'primary_specialty', label: 'Primary specialty', required: true }, { name: 'subspecialties', label: 'Subspecialties', optional: true }, { name: 'licence_number', label: 'Professional licence number', required: true }, { name: 'licensing_authority', label: 'Licensing authority', required: true }, { name: 'licence_jurisdiction', label: 'Licence country or jurisdiction', required: true }, { name: 'licence_issue_date', label: 'Licence issue date', type: 'date', required: true }, { name: 'licence_expiration', label: 'Licence expiration', type: 'date', required: true }, { name: 'years_experience', label: 'Years of experience', type: 'number', required: true }, { name: 'qualifications', label: 'Qualifications', type: 'textarea', required: true }, { name: 'training_institution', label: 'Medical school or training institution', required: true }] },
    { title: 'Hospital membership', description: 'Accept an invitation or request approval from an existing registered hospital.', fields: [{ name: 'invitation_token', label: 'Secure hospital invitation', required: true }, { name: 'registered_hospital_id', label: 'Registered hospital', type: 'select', required: true }, { name: 'department_id', label: 'Department', type: 'select', required: true }, { name: 'staff_role', label: 'Clinical role', type: 'select', required: true, options: ['Doctor', 'Specialist'] }, { name: 'employment_type', label: 'Employment type', required: true }, { name: 'employee_number', label: 'Employee or staff number', required: true }, { name: 'work_start_date', label: 'Work start date', type: 'date', required: true }, { name: 'working_schedule', label: 'Typical working schedule', type: 'textarea', required: true }] },
    { title: 'Account security', description: 'Submission does not grant patient-record access.', fields: security },
  ] },
  hospital: { role: 'hospital', name: 'Hospital', description: 'Register a hospital, its routing location, capabilities and authorized administrator.', access: 'Pending facility verification. Routing remains disabled until approval.', loginPath: '/hospital/login', steps: [
    { title: 'Organization', description: 'Legal and regulatory identity.', fields: [{ name: 'legal_name', label: 'Legal hospital name', required: true }, { name: 'display_name', label: 'Public or display name', required: true }, { name: 'hospital_type', label: 'Hospital type', required: true }, { name: 'ownership_type', label: 'Ownership type', type: 'select', required: true, options: ['Public', 'Private', 'Faith-based', 'Other'] }, { name: 'registration_number', label: 'Registration number', required: true }, { name: 'licence_number', label: 'Facility licence number', required: true }, { name: 'regulatory_authority', label: 'Licensing or regulatory authority', required: true }, ...identity.slice(5, 7), { name: 'city', label: 'City', required: true }, { name: 'official_phone', label: 'Official phone', type: 'tel', required: true }, { name: 'website', label: 'Website', optional: true }, { name: 'operating_hours', label: 'Operating hours', required: true }] },
    { title: 'Location and routing', description: 'Coordinates are validated for nearest-hospital routing.', fields: [...location, { name: 'ambulance_available', label: 'Ambulance availability', type: 'select', required: true, options: ['Available', 'Not available'] }, { name: 'emergency_receiving', label: 'Emergency receiving capability', type: 'select', required: true, options: ['Yes', 'No'] }, { name: 'accepts_referrals', label: 'Accept referrals', type: 'select', required: true, options: ['Yes', 'No'] }] },
    { title: 'Clinical capabilities', description: 'Capabilities remain unverified until reviewed.', fields: [{ name: 'departments', label: 'Available departments', type: 'textarea', required: true }, { name: 'specialties', label: 'Available specialties', type: 'textarea', required: true }, { name: 'bed_capacity', label: 'Bed capacity', type: 'number', required: true }, { name: 'emergency_capacity', label: 'Emergency capacity', type: 'number', required: true }, { name: 'services', label: 'ICU, theatre, lab, pharmacy, imaging and accessibility services', type: 'textarea', required: true }] },
    { title: 'Primary administrator', description: 'The administrator must be authorized by the hospital.', fields: organizationAdmin },
    { title: 'Verification', description: 'List the private documents prepared for secure upload.', fields: [{ name: 'verification_documents', label: 'Registration, operating licence and authorization documents', type: 'textarea', required: true }] },
  ] },
  clinic: { role: 'clinic', name: 'Clinic', description: 'Register an outpatient or specialist clinic and its verified capabilities.', access: 'Pending facility verification.', loginPath: '/auth/login', steps: [
    { title: 'Organization', description: 'Clinic identity and licensing.', fields: [{ name: 'legal_name', label: 'Legal clinic name', required: true }, { name: 'clinic_type', label: 'Clinic type', required: true }, { name: 'registration_number', label: 'Registration number', required: true }, { name: 'licence_number', label: 'Facility licence', required: true }, { name: 'regulatory_authority', label: 'Licensing authority', required: true }, { name: 'ownership_type', label: 'Ownership type', required: true }, ...identity.slice(5, 7), { name: 'official_phone', label: 'Official phone', type: 'tel', required: true }] },
    { title: 'Location', description: 'Confirm the clinic routing location.', fields: location },
    { title: 'Services', description: 'Describe outpatient capacity without claiming unverified hospital capabilities.', fields: [{ name: 'operating_hours', label: 'Operating hours', required: true }, { name: 'outpatient_services', label: 'Outpatient services', type: 'textarea', required: true }, { name: 'departments', label: 'Departments', type: 'textarea', required: true }, { name: 'specialties', label: 'Specialties', type: 'textarea', required: true }, { name: 'daily_capacity', label: 'Daily patient capacity', type: 'number', required: true }, { name: 'referral_hospitals', label: 'Referral hospitals', type: 'textarea', required: true }, { name: 'hmo_plans', label: 'HMO plans accepted', type: 'textarea', optional: true }] },
    { title: 'Administrator', description: 'Authorized clinic account holder.', fields: organizationAdmin },
  ] },
  nurse: { role: 'nurse', name: 'Nurse', description: 'Create a personal account and join a registered hospital through verified membership.', access: 'Hospital invitation preferred. Membership requests remain pending employer approval.', loginPath: '/auth/login', steps: [
    { title: 'Personal identity', description: 'Use your legal identity and work email.', fields: [{ name: 'full_name', label: 'Full legal name', required: true }, { name: 'phone', label: 'International phone', type: 'tel', required: true }, { name: 'email', label: 'Work email', type: 'email', required: true }, { name: 'country', label: 'Country', required: true }, { name: 'region', label: 'Region', required: true }] },
    { title: 'Hospital membership', description: 'Invitation details are protected; join requests require hospital approval.', fields: [{ name: 'invitation_token', label: 'Secure hospital invitation', required: true }, { name: 'registered_hospital_id', label: 'Registered hospital', type: 'select', required: true }, { name: 'department_id', label: 'Department', type: 'select', required: true }, { name: 'employment_type', label: 'Employment type', required: true }, { name: 'employee_number', label: 'Employee or staff number', required: true }, { name: 'work_start_date', label: 'Work start date', type: 'date', required: true }] },
    { title: 'Professional details', description: 'Employment is still confirmed by the inviter.', fields: [{ name: 'nursing_category', label: 'Nursing category', required: true }, { name: 'licence_number', label: 'Registration or licence number', required: true }, { name: 'licensing_authority', label: 'Licensing council', required: true }, { name: 'licence_jurisdiction', label: 'Licence jurisdiction', required: true }, { name: 'licence_expiration', label: 'Licence expiration', type: 'date', required: true }, { name: 'qualifications', label: 'Qualifications', type: 'textarea', required: true }, { name: 'years_experience', label: 'Years of experience', type: 'number', required: true }, { name: 'clinical_skills', label: 'Clinical skills', type: 'textarea', required: true }, { name: 'nursing_focus', label: 'Clinical or nursing focus', required: true }, { name: 'shift_type', label: 'Shift type', required: true }] },
    { title: 'Account security', description: 'Access remains disabled until employer approval.', fields: security },
  ] },
  pharmacy: { role: 'pharmacy', name: 'Pharmacy', description: 'Register a pharmacy and responsible pharmacist for verification.', access: 'Pending pharmacy and licence verification.', loginPath: '/auth/login', steps: [
    { title: 'Organization', description: 'Pharmacy and premises licensing.', fields: [{ name: 'legal_name', label: 'Legal pharmacy name', required: true }, { name: 'trading_name', label: 'Trading name', required: true }, { name: 'pharmacy_type', label: 'Pharmacy type', required: true }, { name: 'registration_number', label: 'Registration number', required: true }, { name: 'licence_number', label: 'Premises licence number', required: true }, { name: 'regulatory_authority', label: 'Regulatory authority', required: true }, { name: 'responsible_professional', label: 'Superintendent pharmacist name', required: true }, { name: 'responsible_professional_licence', label: 'Superintendent licence number', required: true }, ...identity.slice(5, 7)] },
    { title: 'Location and service', description: 'Location supports safe prescription routing.', fields: [...location, { name: 'official_phone', label: 'Official phone', type: 'tel', required: true }, { name: 'operating_hours', label: 'Operating hours', required: true }, { name: 'service_area', label: 'Service area', required: true }, { name: 'hmo_plans', label: 'HMO plans accepted', optional: true }] },
    { title: 'Operations', description: 'Capabilities are verified before prescription access.', fields: [{ name: 'services', label: 'Dispensing, cold-chain, delivery, pickup and emergency medicine services', type: 'textarea', required: true }, { name: 'inventory_integration', label: 'Inventory integration requirements', type: 'textarea', optional: true }] },
    { title: 'Administrator', description: 'Authorized pharmacy account holder.', fields: organizationAdmin },
  ] },
  laboratory: { role: 'laboratory', name: 'Laboratory', description: 'Register an accredited diagnostic or imaging laboratory.', access: 'Pending laboratory accreditation verification.', loginPath: '/auth/login', steps: [
    { title: 'Organization', description: 'Laboratory identity and accreditation.', fields: [{ name: 'legal_name', label: 'Legal laboratory name', required: true }, { name: 'laboratory_type', label: 'Laboratory type', required: true }, { name: 'registration_number', label: 'Registration number', required: true }, { name: 'accreditation_number', label: 'Accreditation number', required: true }, { name: 'regulatory_authority', label: 'Accreditation authority', required: true }, { name: 'responsible_professional', label: 'Responsible laboratory scientist', required: true }, { name: 'responsible_professional_licence', label: 'Professional licence number', required: true }, ...identity.slice(5, 7)] },
    { title: 'Location', description: 'Confirm collection and result-service location.', fields: location },
    { title: 'Services', description: 'Describe verified operational scope.', fields: [{ name: 'operating_hours', label: 'Operating hours', required: true }, { name: 'collection_sites', label: 'Sample collection sites', type: 'textarea', required: true }, { name: 'tests_offered', label: 'Tests offered', type: 'textarea', required: true }, { name: 'equipment_categories', label: 'Equipment categories', type: 'textarea', required: true }, { name: 'turnaround_times', label: 'Turnaround-time ranges', type: 'textarea', required: true }, { name: 'result_delivery', label: 'Result-delivery methods', type: 'textarea', required: true }] },
    { title: 'Administrator', description: 'Authorized laboratory account holder.', fields: organizationAdmin },
  ] },
  hmo: { role: 'hmo', name: 'HMO', description: 'Register a payer organization and its regulated authorization workflows.', access: 'Pending payer and regulatory verification.', loginPath: '/auth/login', steps: [
    { title: 'Organization', description: 'Legal and regulatory identity.', fields: [{ name: 'legal_name', label: 'Legal organization name', required: true }, { name: 'trading_name', label: 'Trading name', required: true }, { name: 'organization_type', label: 'Organization type', required: true }, { name: 'registration_number', label: 'Regulatory registration number', required: true }, { name: 'regulatory_authority', label: 'Regulatory authority', required: true }, ...identity.slice(5, 7), { name: 'head_office_address', label: 'Head-office address', type: 'textarea', required: true }, { name: 'website', label: 'Website', optional: true }] },
    { title: 'Operations', description: 'Member and provider network scope.', fields: [{ name: 'regions_served', label: 'States or regions served', type: 'textarea', required: true }, { name: 'member_service_phone', label: 'Member-service phone', type: 'tel', required: true }, { name: 'claims_email', label: 'Claims email', type: 'email', required: true }, { name: 'authorization_contact', label: 'Authorization contact', required: true }, { name: 'plans_offered', label: 'Health plans offered', type: 'textarea', required: true }, { name: 'claims_method', label: 'Claims-processing method', type: 'textarea', required: true }, { name: 'authorization_workflow', label: 'Authorization workflow', type: 'textarea', required: true }, { name: 'integration_requirements', label: 'API or integration requirements', type: 'textarea', optional: true }] },
    { title: 'Administrator', description: 'Authorized payer account holder.', fields: organizationAdmin },
    { title: 'Verification', description: 'List regulatory documents prepared for secure upload.', fields: [{ name: 'verification_documents', label: 'Verification documents', type: 'textarea', required: true }] },
  ] },
  government: { role: 'government', name: 'Government', description: 'Apply for authorized public-health reporting access.', access: 'Invitation or reviewed application only. Patient-level data is never granted automatically.', loginPath: '/auth/login', steps: [
    { title: 'Authorization', description: 'Provide an invitation or authorization document reference.', fields: [{ name: 'invitation_token', label: 'Signed invitation token', optional: true }, { name: 'authorization_document_key', label: 'Authorization document private reference', optional: true }] },
    { title: 'Institution', description: 'Official government identity.', fields: [{ name: 'legal_name', label: 'Government institution name', required: true }, { name: 'agency', label: 'Ministry, department or agency', required: true }, { name: 'government_level', label: 'Government level', type: 'select', required: true, options: ['National', 'State', 'Regional', 'Local'] }, { name: 'country', label: 'Country', required: true }, { name: 'jurisdiction', label: 'Jurisdiction', required: true }, { name: 'official_address', label: 'Official address', type: 'textarea', required: true }, { name: 'official_email', label: 'Official domain email', type: 'email', required: true }] },
    { title: 'Applicant', description: 'The named official remains pending agency verification.', fields: [{ name: 'full_name', label: 'Staff full name', required: true }, { name: 'official_title', label: 'Official title', required: true }, { name: 'employee_number', label: 'Employee number', required: true }, { name: 'work_phone', label: 'Work phone', type: 'tel', required: true }, { name: 'supervising_official', label: 'Supervising official', required: true }] },
    { title: 'Requested access', description: 'Only aggregated or legally authorized data may be approved.', fields: [{ name: 'responsibilities', label: 'Dashboard responsibilities', type: 'textarea', required: true }, { name: 'geographic_scope', label: 'Requested geographic scope', type: 'textarea', required: true }, { name: 'reporting_permissions', label: 'Reporting permissions requested', type: 'textarea', required: true }] },
  ] },
  'platform-admin': { role: 'platform-admin', name: 'Platform administrator', description: 'Accept a single-use invitation for a scoped administration role.', access: 'Invitation only. No public administrator self-registration.', loginPath: '/auth/login', steps: [
    { title: 'Invitation', description: 'The invitation fixes the maximum administrator role.', fields: [{ name: 'invitation_token', label: 'Single-use invitation', required: true }, { name: 'email', label: 'Invited work email', type: 'email', required: true }] },
    { title: 'Identity and role', description: 'Role escalation through this form is blocked server-side.', fields: [{ name: 'full_name', label: 'Full name', required: true }, { name: 'phone', label: 'Phone', type: 'tel', required: true }, { name: 'country', label: 'Country', required: true }, { name: 'admin_role', label: 'Assigned administrator role', type: 'select', required: true, options: ['SUPER_ADMIN', 'SECURITY_ADMIN', 'COMPLIANCE_ADMIN', 'TENANT_REVIEWER', 'SUPPORT_ADMIN', 'AUDITOR'] }] },
    { title: 'Security', description: 'Multi-factor authentication is required.', fields: [...security, { name: 'mfa_method', label: 'MFA method', type: 'select', required: true, options: ['Authenticator app', 'Security key'] }, { name: 'recovery_confirmation', label: 'Recovery-code confirmation', required: true }, { name: 'security_policy_acceptance', label: 'Type ACCEPT to confirm the security policy', required: true }] },
  ] },
};

export const signupRoles = Object.values(signupConfigs);
